run_mod: debug
port: :8080
jwt:
  secret: RtgYsliaukijq8s2l9p3a4UQBb7 # jwt签名密钥
  token-access-expire: 7200           # access token  过期时间，7200秒，2个小时
  token-refresh-expire: 2592000       # refresh token 过期时间，30天，单位：秒

log:
  level: debug
  path: "./logs"
  filename: "account.log"
  enable-stdout: true

db:
  dsn: root:123456@tcp(127.0.0.1:3306)/account?charset=utf8  # data source name
  max-idle-connections: 10      # 最大空闲连接数
  max-open-connections: 10      # 最大打开连接数
  max-connection-life-time: 30  # 空闲连接最大存活时间 30s